# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for drivers that support virtualization
#

obj-$(CONFIG_FSL_HV_MANAGER)	+= fsl_hypervisor.o
obj-y				+= vboxguest/
obj-y				+= periscope/
obj-$(CONFIG_KVM_API_TEST)		+= kvm_api_test/

